app-mode = "DEFAULT_APP"
app-mode = ${?APP_MODE}

application {
  actor-system-name = "eid-scala-app"
  actor-system-name = ${?ACTOR_SYSTEM_NAME}
  bind-port = "8080"
  bind-port = ${?HTTP_PORT}
  bind-interface = "0.0.0.0"
  bind-interface = ${?HTTP_BIND_INTERFACE}
}

exchangerate-api {
  base-url = "https://v6.exchangerate-api.com/v6/"
  api-key = "811a781539608ce94426dec8"
  base-currency = "USD"
}

database {
  jdbc-url = "jdbc:postgresql://localhost:5432/evident?user=evident&password=evident"
  jdbc-url = ${?JDBC_URL}
  connection-pool {
    number-of-threads = 10
    number-of-threads = ${?DB_NUM_THREADS}
    queue-size = 1000
    queue-size = ${?DB_QUEUE_SIZE}
  }
}

