application {
  actor-system-name = "test-application"
}

exchangerate-api {
  base-url = "https://v6.exchangerate-api.com/v6/"
  api-key = "811a781539608ce94426dec8" 
  base-currency = "USD"
}

database {
  jdbc-url = ${?JDBC_URL}
  connection-pool {
    number-of-threads = ${?DB_NUM_THREADS}
    queue-size = ${?DB_QUEUE_SIZE}
  }
}
